Alvearie/hri-mgmt-api

.github/workflows/code-scans.yml
.github/workflows/pull_request.yml

Fixed a couple minor issues.
https://jira.wh-sdlc.watson-health.ibm.com/browse/WHFHRI-670

WHFHRI-670

---

.github/workflows/ci-workflow.yml
.github/workflows/code-scans.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

WHFHRI-690: Add slack notification action to ci-workflow

---

.github/workflows/ci-workflow.yml
.github/workflows/code-scans.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

Whfhri 690 2.x

---

.github/workflows/ci-workflow.yml
.github/workflows/code-scans.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

WHFHRI-690: Add slack notification action

---

.github/delete.yml

This is a new PR now merging into `main` instead of the `support-#.x` branches because the delete event can only be triggered from the default branch.

WHFHRI-692:  Add delete workflow for deleting namespaces

---

.github/workflows/ci-workflow.yml
.github/workflows/release.yml
docker/Dockerfile

* Updated Dockle action
* Minor security modifications to the Docker build

WHFHRI-694

---

.github/workflows/ci-workflow.yml
.github/workflows/release.yml
docker/Dockerfile

* Updated Dockle action
* Added vulnerability exceptions
* Minor security modifications to the Docker build

WHFHRI-694 2.x

---

.github/workflows/ci-workflow.yml
.github/workflows/release.yml
docker/Dockerfile

* Updated Dockle action
* Added vulnerability exceptions
* Minor security modifications to the Docker build

WHFHRI-694 1.x

---

test/spec/hri_management_api_spec.rb

WHFHRI-717 1.x

---

.github/workflows/release.yml

Added push to WH commons container registry in the release workflow.

WHFHRI-728

---

.github/workflows/release.yml

Added push to WH commons container registry in the release workflow.

WHFHRI-728 1.x

---

.github/workflows/ci-workflow.yml
.gitignore
run-dreddtests.sh
test/spec/hri_deploy_helper.rb
test/spec/hri_management_api_no_validation_spec.rb
test/spec/hri_management_api_validation_spec.rb

Put all the IVT test logs of the Mgmt API in `/test/logs` and added archival in the ci-workflow on failure. This is for debugging IVT test failiures in GitHub Actions.

WHFHRI-737

---

.github/workflows/ci-workflow.yml
.github/workflows/code-scans.yml
.github/workflows/pull_request.yml
README.md
docker/Dockerfile
src/go.mod

Signed-off-by: Dan Baxter <dan.baxter240@gmail.com>

WHFHRI-524: Upgrade to go 1.17

---

test/spec/upload_test_reports.rb

Signed-off-by: Fred Ricci <60147759+FRicci618@users.noreply.github.com>

Upload the latest test report only

---

.github/pull_request_template.md
.github/workflows/delete.yml
README.md
docker/Dockerfile
test/spec/upload_test_reports.rb

WHFHRI-725, pre-release merge from main

---

test/spec/hri_management_api_no_validation_spec.rb

Refactor test to delete tenant stream

---

mgmt-api-manifest.yml

Signed-off-by: Alisa Kotliarova <alisa@ibm.com>

Update release number

---

.github/workflows/ci-workflow.yml

Fixed IBM cloud Toolchain trigger

---

config.yml
src/common/config/config.go
src/common/kafka/admin.go
src/serve.go
src/streams/create.go
src/streams/create_test.go
src/streams/handler.go
src/tenants/handler.go

https://jira.wh-sdlc.watson-health.ibm.com/browse/JIRA_TICKET_HERE](https://jira.wh-sdlc.watson-health.ibm.com/browse/WHFHRI-822
https://jira.wh-sdlc.watson-health.ibm.com/browse/WHFHRI-824

create and delete stream end point changes

---

config.yml
src/common/model/requests.go
src/mongoApi/client.go
src/serve.go
src/tenants/get.go
src/tenants/handler.go

Whfhri 779

---

src/tenants/handler.go

Adding explicit validation for tennat creation

---

src/batches/create.go
src/batches/handler.go
src/common/auth/hri_claims.go
src/common/auth/validate.go
src/common/kafka/writer.go
src/common/model/requests.go
src/mongoApi/utility.go
src/serve.go
src/streams/handler.go
src/tenants/handler.go

create batch API changes

---

src/batches/create.go
src/batches/get.go
src/batches/handler.go
src/common/model/requests.go
src/serve.go

Adding Batch get request

---

src/batches/create.go
src/batches/get.go
src/batches/get_by_batch_id.go
src/common/model/requests.go
src/tenants/create.go
src/tenants/delete.go
src/tenants/get.go
src/tenants/get_by_id.go

Updating tenantId

---

src/batches/get_by_batch_id.go
src/common/model/requests.go
src/common/param/parameters.go

get batch metadata update

---

src/common/auth/validate.go

Whfhri tenant validate

---

src/batches/get_by_batch_id.go
src/mongoApi/client.go

Batch Defect 2 Fix

---

src/common/auth/validate.go
src/common/model/requests.go
src/tenants/create.go

WHFHRI-1120 and WHFHRI-1121 Fixes

---

src/batches/get_by_batch_id.go
src/batches/handler.go
src/batches/send_fail.go
src/batches/send_status_complete.go
src/batches/terminate_status.go
src/healthcheck/get_check.go
src/serve.go

adding batch status treminate

---

src/common/auth/constants.go
src/common/auth/hri_claims.go

adding common method to get auth role
